version: '3'

services:
  full-teaching-postgresql:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=full-teaching
      - POSTGRES_USER=postgres

  full-teaching-openvidu-server-kms:
    image: openvidu/openvidu-server-kms:latest
    ports:
      - 4443:4443
    environment:
      - KMS_STUN_IP=stun.l.google.com
      - KMS_STUN_PORT=19302
      - openvidu.secret=MY_SECRET
      - openvidu.publicurl=docker

  full-teaching:
    image: full-teaching:1.0
    links:
      - full-teaching-postgresql
      - full-teaching-openvidu-server-kms
    depends_on:
      - full-teaching-postgresql
      - full-teaching-openvidu-server-kms
    ports:
      - 5001:5001
    environment:
      - WAIT_HOSTS=full-teaching-postgresql:5432
      - WAIT_HOSTS_TIMEOUT=120
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=full-teaching
      - POSTGRES_USER=postgres
      - server.port=5001
      - openvidu.url=https://full-teaching-openvidu-server-kms:4443
      - openvidu.secret=MY_SECRET
