apiVersion: v1
kind: Service
metadata:
  annotations:
    io.elastest: "true"
  creationTimestamp: null
  labels:
    io.elastest: "true"
    io.elastest.service: full-teaching-mysql-service
    io.elastest.service.type: SUT
  name: full-teaching-mysql
spec:
  ports:
  - name: "full-teaching-mysql-3306-node-port"
    port: 3306
    targetPort: 3306
    nodePort: 3306
  selector:
    io.elastest.service: full-teaching-mysql
  type: NodePort
status:
  loadBalancer: {}